from django.urls import path
from .views import (
                    SignUpView, 
                    LoginView, 
                    UserLogout, 
                    DeleteUser, 
                    CategoriesListView, 
                    CategoriesDetailView,
                    CategoriesDetailView2,
                    CategoriesCreateView,
                    ProductCreate,
                    ProductDelete,
                    ProductDetail,
                    ProductsList,
                    ProductUpdate,
                    PopularList, 
                    ProductList, 
                    CategoryInCategoriesListView,
                    ProductsList2,
                    HandleCart,
                    )
app_name="api"

urlpatterns = [
    # path('a/', getRoutes, name='routes'),
    # path('popular/', ProductList.as_view(), name='product-list'),
    path('popular/', PopularList.as_view(), name='product-list'),
    path('product/', ProductList.as_view(), name='product'),
    path('products/', ProductsList.as_view(), name='product-list'),
    path('products2/', ProductsList2.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('products/create/', ProductCreate.as_view(), name='product-create'),
    path('products/<int:pk>/delete/', ProductDelete.as_view(), name='product-delete'),
    path('products/<int:pk>/update/', ProductUpdate.as_view(), name='product-update'),
    # path('register/', SignUpView.as_view(), name='register'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', UserLogout.as_view(), name='logout'),
    # path('delete/', DeleteUser.as_view(), name='delete'),
    path('categories/', CategoriesListView.as_view(), name='category_list'),
    path('categorin/', CategoryInCategoriesListView.as_view(), name='CategoryInCategoriesListView'),
    path('categories/<int:pk>/', CategoriesDetailView.as_view(), name='category_detail'),
    path('categorin/<int:pk>/', CategoriesDetailView2.as_view(), name='CategoryInCategoriesListView'),
    path('categories/create/', CategoriesCreateView.as_view(), name='category_create'),
    path('get_cart/', HandleCart.as_view(), name='get_cart'),
]
